version: '3.0'
services:
    api:
        image: techniqal/api:0.0.1
        build: 
            context: api/
            dockerfile: Dockerfile-api
        ports:
            - "3333:3333"
        environment:
            - PORT=3333
        volumes:
            - ./api/db_big.json:/api/db.json
