FROM ubuntu:18.04

LABEL maintainer="adrian.gonciarz@gmail.com"

RUN apt update && apt install curl -y

ENV CURL_HOST https://google.pl
ENV EMAIL aaa@example.com

CMD curl -L $CURL_HOST && echo $EMAIL
